/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GlossarRouteImport } from './routes/glossar'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen.$slug'

const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarRoute = GlossarRouteImport.update({
  id: '/glossar',
  path: '/glossar',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSlugRoute = LeistungenSlugRouteImport.update({
  id: '/leistungen/$slug',
  path: '/leistungen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/glossar': typeof GlossarRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unternehmen': typeof UnternehmenRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/glossar': typeof GlossarRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unternehmen': typeof UnternehmenRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/glossar': typeof GlossarRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unternehmen': typeof UnternehmenRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/glossar'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/referenzen'
    | '/sitemap.xml'
    | '/unternehmen'
    | '/leistungen/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/glossar'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/referenzen'
    | '/sitemap.xml'
    | '/unternehmen'
    | '/leistungen/$slug'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/glossar'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/referenzen'
    | '/sitemap.xml'
    | '/unternehmen'
    | '/leistungen/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GlossarRoute: typeof GlossarRoute
  ImpressumRoute: typeof ImpressumRoute
  KarriereRoute: typeof KarriereRoute
  KontaktRoute: typeof KontaktRoute
  ReferenzenRoute: typeof ReferenzenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnternehmenRoute: typeof UnternehmenRoute
  LeistungenSlugRoute: typeof LeistungenSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossar': {
      id: '/glossar'
      path: '/glossar'
      fullPath: '/glossar'
      preLoaderRoute: typeof GlossarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$slug': {
      id: '/leistungen/$slug'
      path: '/leistungen/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  GlossarRoute: GlossarRoute,
  ImpressumRoute: ImpressumRoute,
  KarriereRoute: KarriereRoute,
  KontaktRoute: KontaktRoute,
  ReferenzenRoute: ReferenzenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnternehmenRoute: UnternehmenRoute,
  LeistungenSlugRoute: LeistungenSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
